[package]
name = "donuthle"
version = "0.1.1"
edition = "2021"
description = "Experimental high-level emulator for Android 1.x applications"
license = "MIT"
repository = "https://github.com/KlugKlugTG/DonutHLE"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1"
byteorder = "1"
clap = { version = "4", features = ["derive"] }
jpeg-decoder = "0.3"
png = "0.17"
zip = "2"

[dev-dependencies]
tempfile = "3"
